backend:
  name: git-gateway
  repo: [konstunge]/kajsaunge.github.io
  branch: master
  site_domain: [kajsaunge].github.io
media_folder: public/img
public_folder: img
publish_mode: editorial_workflow
collections:
  - name: "pages"
    label: "Pages"
    files:
      - label: "Kontakt"
        name: "kontakt"
        file: "content/art.md"
        fields:
          - { label: "Title", name: "title", widget: "string" }
          - { label: "Publish Date", name: "date", widget: "datetime" }
          - { label: "Body", name: "body", widget: "markdown" }
          - label: "Cats"
            name: "cats"
            widget: list
            fields:
              - { label: "Name", name: "name", widget: "string" }
              - { label: "Description", name: "description", widget: "text" }
